first part of data table, and mentors page is ready
MentorsWithoutBorders/mwb-partners-admin pull request #35
Opened 2023-07-17 18:27 UTC by surenabrahamyan

Hey team,

I wanted to share an update with you all. I've made significant progress on the mentors page and the data table functionality. However, as the complexity of these features increases, I believe it's a good point to pause and create an intermediate pull request. This will allow you all to review the changes, provide feedback, and guide me in the right direction.

Please feel free to make any corrections, suggestions, recommendations, or offer guidance as needed. Since I'm still relatively new to front-end development, I want to ensure that I'm on the right path. Your expertise and input are greatly appreciated.

I'm really excited about this milestone, and I look forward to your feedback. Let's collaborate to make this project a success!

Best regards,
Suren

2023-07-18 10:17 UTC, Mr777Nick requested changes
I have some comments on a couple of minor changes, mainly just for code standardization. @surenabrahamyan

2023-07-18 10:17 UTC, Mr777Nick commented on src/api/mentors.tsx
I think this file extension should just be `.ts` instead of `.tsx` since it doesn't return any component. @surenabrahamyan

2023-07-18 10:17 UTC, Mr777Nick commented on src/components/table/DataTable.tsx
> +const FilterButton = styled(Button)(({ theme }) => ({
Let's move these styled components into a different file with the naming of `ComponentName.styled.ts` to not clutter the component itself. @surenabrahamyan

2023-07-18 10:17 UTC, Mr777Nick commented on src/components/table/DataTable.tsx
> +  const [page, setPage] = React.useState(0)
I prefer to import the `useState`, `useEffect`, or any other hooks and not import the whole React library. Looks cleaner and tidier too since we can use `useState` instead of `React.useState`.

wdyt? @MentorsWithoutBorders/fe-team-mwb-partners-admin

2023-07-18 10:17 UTC, Mr777Nick commented on src/components/table/SearchFilterField.tsx
> +const FilterInputLabel = styled(InputLabel)(({ theme }) => ({
Let's move those styled components as well! @surenabrahamyan

2023-07-18 10:17 UTC, Mr777Nick commented on src/components/table/interfaces.tsx
Also since these are returning any components, let's use `.ts` extension. @surenabrahamyan

2023-08-01 19:49 UTC, surenabrahamyan commented
Hi guys,

Here I tried to fix all comments that you left in first PR.

Also add full functionality for data table including custom data handling by providing list data fetch api and table columns data.

Also created Modal view which will be called when we click on info button for each row in data table and modal component will do fetch for custom data ID and show it inside.

2023-08-01 19:53 UTC, surenabrahamyan commented
<img width="1468" alt="image" src="https://github.com/MentorsWithoutBorders/mwb-partners-admin/assets/93602276/55716046-1663-4439-bbe9-e13c1f59c501">

2023-08-01 19:53 UTC, surenabrahamyan commented
<img width="1468" alt="image" src="https://github.com/MentorsWithoutBorders/mwb-partners-admin/assets/93602276/790eaada-ca14-46e0-81ea-a81ff28be391">

2023-08-16 09:50 UTC, Mr777Nick requested changes
Hi @surenabrahamyan, functionality looks good! 
Just some comments left regarding some of the styled-components that you missed and the usage of MUI color palette. I think it should be a quick fix, seeing that you've moved some styled components into its own file.

2023-08-16 09:50 UTC, Mr777Nick commented on src/components/table/DataModal.tsx
> +const innerModalStyle: SxProps<Theme> = {
Can this innerModalStyle also be moved into its own *.styled.ts file?

2023-08-16 09:50 UTC, Mr777Nick commented on src/components/table/DataTable.tsx
> +const tablePaperStyle: SxProps<Theme> = {
It's the same as the previous comment about moving styled components.

2023-09-10 07:04 UTC, Mr777Nick approved these changes

2023-09-10 10:50 UTC, merged