Issue #19 - Implement Dropdown Menu (in progress)
MentorsWithoutBorders/mwb-partners-admin pull request #37
Opened 2023-07-19 02:38 UTC by jfmdev

Fix issue #19

2023-07-24 17:44 UTC, edmondpr approved these changes

2023-07-25 11:43 UTC, Mr777Nick requested changes
Hi @jfmdev, added some comments for minor changes, functionality LGTM!

2023-07-25 11:43 UTC, Mr777Nick commented on src/pages/app/students.tsx
> +  FormControl,
Forgot to mention this on another PR, but can you use path imports instead of named imports on this one?
So instead of 
`import { Button, TextField } from '@mui/material';`
we're going with
`import Button from '@mui/material/Button';
import TextField from '@mui/material/TextField';`

More about this on this documentation on MUI:
https://mui.com/material-ui/guides/minimizing-bundle-size/#option-one-use-path-imports

2023-07-25 11:43 UTC, Mr777Nick commented on src/pages/app/students.tsx
> +const selectButtonStyle: SxProps<Theme> = {
Let's move those styled components into a dedicated file.
As per the discussion on the channel, for any styled components inside a `pages` component, we should put it on `src\styles\pages\<same folder & files structure as the pages component>` so in this case it will be `src\styles\pages\app\students.styled.ts`.

2023-07-26 20:47 UTC, ugudlado commented
@jfmdev I have some overlapping changes here: https://github.com/MentorsWithoutBorders/mwb-partners-admin/tree/57-mentors-table-projects-dropdown

2023-07-28 21:35 UTC, jfmdev commented
@Mr777Nick I updated the PR according to your comments

2023-07-28 21:38 UTC, jfmdev commented
@ugudlado Thanks for the heads up, I can later update my code to use the `DropDown` component you are implementing.

2023-07-28 23:22 UTC, Mr777Nick approved these changes

2023-07-29 14:34 UTC, merged