8-students-table-video-testimonials
MentorsWithoutBorders/mwb-partners-admin pull request #92
Opened 2023-10-29 23:04 UTC by Mohmed-Refaay

https://github.com/MentorsWithoutBorders/mwb-partners-admin/assets/69407428/2bf81a04-8032-4591-814e-8af8494e0ae7

2023-10-31 21:00 UTC, edmondpr requested changes

2023-10-31 21:00 UTC, edmondpr commented on src/components/Table/StudentsTable/StudentsTable.tsx
> +                  title={params.row.name}
The title value should actually be `testimonial.uploadedDateTime` (in MMM DD, YYYY format) instead of `params.row.name`.

2023-10-31 21:00 UTC, edmondpr commented on src/components/Table/StudentsTable/StudentsTable.tsx
> +                  link={testimonial}
The link value should be `testimonial.url` instead of `testimonial`.

2023-10-31 21:52 UTC, Mohmed-Refaay commented on src/components/Table/StudentsTable/StudentsTable.tsx
> +                  link={testimonial}
Is the BE updated now?

2023-10-31 22:59 UTC, edmondpr commented on src/components/Table/StudentsTable/StudentsTable.tsx
> +                  link={testimonial}
Oh you're right, we had that discussion. I actually did a test locally and it seemed to work both for `uploadedDateTime` and for `url`.

2023-11-01 23:54 UTC, Mohmed-Refaay commented on src/components/Table/StudentsTable/StudentsTable.tsx
> +                  link={testimonial}
@edmondpr I have updated them, thanks

2023-11-02 17:36 UTC, edmondpr approved these changes

2023-11-02 17:36 UTC, merged